dunkdynasty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
    # built-in authentication
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('franchises/all/', views.franchises_index, name='franchises_index'),
    path('franchises/', views.franchises_my_index, name='franchises_my_index'),
    path('franchises/<int:franchise_id>/', views.franchises_detail, name='franchises_detail'),
    path('franchises/create/', views.FranchiseCreate.as_view(), name='franchises_create'),
    path('franchises/<int:pk>/update/', views.FranchiseUpdate.as_view(), name='franchises_update'),
    path('franchises/<int:pk>/delete/', views.FranchiseDelete.as_view(), name='franchises_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('franchises/<int:franchise_id>/add_photo/', views.add_photo, name='add_photo'),
    path('franchises/<int:franchise_id>/search/', views.players_search, name='players_search'),
    path('franchises/<int:franchise_id>/get_players/', views.get_players, name='get_players'),
    path('franchises/<int:franchise_id>/add_player/', views.add_player, name='add_player'),
    path('franchises/<int:franchise_id>/player/<int:player_id>/', views.player_cut, name='player_cut'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# Import the User
from django.contrib.auth.models import User

# Create your models here.
class Franchise(models.Model):
    city = models.CharField(max_length=25)
    name = models.CharField(max_length=25)
    motto = models.CharField(max_length=100)
    established = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.city} {self.name}"

    # redirect when creating and updating a franchise
    def get_absolute_url(self):
        return reverse('franchises_detail', kwargs={
            'franchise_id': self.id
        })


class Photo(models.Model):
    url = models.CharField(max_length=200)
    franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE)
    # franchise = models.OneToOneField(Franchise, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"Photo for franchise_id: {self.franchise_id} at {self.url}"


class Player(models.Model):
    id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    position = models.CharField(max_length=3, null=True)
    height = models.CharField(null=True)
    # height_inches = models.IntegerField(null=True)
    weight = models.IntegerField(null=True)
    franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name} on franchise_id: {self.franchise_id}"

main_app/forms.py
from django.forms import ModelForm
from .models import Player

class SearchForm(ModelForm):
    class Meta:
        model = Player
        fields = ['first_name']

class AddPlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['id']
    

main_app/views.py
import uuid
import boto3
import os
import requests
# from django.http import JsonResponse
from django.shortcuts import render, redirect
# Import for CBV
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Import for redirect
from django.urls import reverse_lazy
# Import for signup
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Import for Authorization
from django.contrib.auth.decorators import login_required
# Import mixin for CBV Authorization
from django.contrib.auth.mixins import LoginRequiredMixin
# Import models
from .models import Franchise, Photo, Player
from .forms import SearchForm, AddPlayerForm

# Create your views here.

# HOME VIEW
def home(request):
    return render(request, 'home.html')

# ABOUT VIEW
def about(request):
    return render(request, 'about.html')

# FRANCHISES INDEX - ALL FRANCHISES
def franchises_index(request):
    franchises = Franchise.objects.all()
    return render(request, 'franchises/index.html', {
        'franchises': franchises
    })

# MY FRANCHISES INDEX - LOGGED IN USERS FRANCHISES
@login_required
def franchises_my_index(request):
    my_franchises = Franchise.objects.filter(user=request.user)
    if len(my_franchises) == 0:
        return redirect('franchises_create')
    else:
        return render(request, 'franchises/my_index.html', {
            'my_franchises': my_franchises
    })

# FRANCHISES DETAIL
def franchises_detail(request, franchise_id):
    franchise = Franchise.objects.get(id=franchise_id)
    return render(request, 'franchises/detail.html', {
        'franchise': franchise
    })

# FRANCHISES CREATE
class FranchiseCreate(LoginRequiredMixin, CreateView):
    model = Franchise
    fields = ['city', 'name', 'motto']

    def form_valid(self, form):
        # form.instance is the unsaved franchise object
        form.instance.user = self.request.user
        return super().form_valid(form)

# FRANCHISES UPDATE
class FranchiseUpdate(LoginRequiredMixin, UpdateView):
    model = Franchise
    fields = ['city', 'name', 'motto']

# FRANCHISES DELETE
class FranchiseDelete(LoginRequiredMixin, DeleteView):
    model = Franchise
    success_url = reverse_lazy('franchises_index')

# SIGNUP
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # save user to db
            user = form.save()
            login(request, user)
            return redirect('franchises_index')
        else:
            error_message = 'Invalid sign up, please try again.'
    # Invalid POST or GET request
    form = UserCreationForm()
    context = {
        'form': form,
        'error_message': error_message}
    return render(request, 'registration/signup.html', context)

# ADD PHOTO
@login_required
def add_photo(request, franchise_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # Need unique key for s3 (filename)
        # Keep the same file extension as uploaded file by slicing
        uniqueId = uuid.uuid4().hex[:6]
        extension = photo_file.name[photo_file.name.rfind('.'):]
        key = uniqueId + extension
        # try uploading file
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build full url
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, franchise_id=franchise_id)
            return redirect('players_search', franchise_id=franchise_id)
        except Exception as e:
            print('An error occured uploading file to S3.')
            print(e)
    return redirect('franchises_detail', franchise_id=franchise_id)

# RENDER PLAYERS SEARCH PAGE
@login_required
def players_search(request, franchise_id):
    franchise = Franchise.objects.get(id=franchise_id)
    # instantiate SearchForm to be rendered
    form = SearchForm()
    return render(request, 'franchises/search.html', {
        'franchise': franchise,
        'franchise_id': franchise_id,
        'form': form
    })

# GET PLAYERS (SEARCH RESULTS)
@login_required
def get_players(request, franchise_id):
    results = {}
    franchise = Franchise.objects.get(id=franchise_id)
    # instantiate AddPlayerForm to be rendered
    add_player_form = AddPlayerForm()
    # check if search form is submitted
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['first_name']
            endpoint = 'https://api.balldontlie.io/v1/players?per_page=10'
            token = os.environ.get('API_TOKEN_BDL')
            headers = {'Authorization': f"{token}"}
            response = requests.get(endpoint, headers=headers, params={'search': query})
            results = response.json()
    else:
        form = SearchForm()
    return render(request, 'franchises/search.html', {
        'form': form,
        'results': results,
        'franchise_id': franchise_id,
        'franchise': franchise,
        'add_player_form': add_player_form
    })

# ADD PLAYER TO FRANCHISE
@login_required
def add_player(request, franchise_id):
    if request.method == 'POST':
        player_id = request.POST.get('player-id')
        endpoint = 'https://api.balldontlie.io/v1/players/'
        token = os.environ.get('API_TOKEN_BDL')
        headers = {'Authorization': f"{token}"}
        response = requests.get(f"{endpoint}{player_id}", headers=headers)
        result = response.json()
        new_player = Player(
            id=result['data']['id'],
            first_name=result['data']['first_name'],
            last_name=result['data']['last_name'],
            position=result['data']['position'],
            height=result['data']['height'],
            weight=result['data']['weight'],
            franchise_id=franchise_id
        )
        if Player.objects.filter(id=player_id).exists():
            # player is already on a franchise
            return redirect('players_search', franchise_id=franchise_id)
        else:
            # player is available to be claimed
            new_player.save()
    return redirect('franchises_detail', franchise_id=franchise_id)

# PLAYER CUT (DELETE)
@login_required
def player_cut(request, franchise_id, player_id):
    player = Player.objects.get(id=player_id)
    player.delete()
    return redirect('franchises_detail', franchise_id=franchise_id)

main_app/templates/franchises/detail.html
{% extends 'base.html' %} {% block content %}
<section
  id="header"
  class="flex flex-col md:flex-row flex-wrap justify-center md:gap-6 mb-12"
>
  <div class="w-full md:w-2/5" id="photo">
    {% for photo in franchise.photo_set.all %} {% if forloop.last %}
    <img
      class="aspect-3/2 rounded mb-4"
      src="{{ photo.url }}"
      alt="Photo for {{ franchise.city }} {{ franchise.name }}"
    />
    {% endif %} {% empty %}
    <img
      class="aspect-3/2 rounded mb-4"
      src="../../static/Assets/franchise-photo-placeholder.jpg"
      alt="Placeholder image"
    />
    {% endfor %} {% if franchise.user == user %}
    <form
      action="{% url 'add_photo' franchise.id %}"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" class="mb-2" />
      <button type="submit" class="btn btn-green mb-6">Upload Photo</button>
    </form>
    {% endif %}
  </div>
  <div class="sm:mt-4" id="franchise-info">
    <h1 class="text-4xl font-bold">
      {{ franchise.city }} {{ franchise.name }}
    </h1>
    <h2 class="mb-2">Owner: {{ franchise.user }}</h2>
    <h3 class="mb-2">Established: {{ franchise.established|date:'N Y' }}</h3>
    <p class="mb-10">{{ franchise.motto }}</p>
    {% if franchise.user == user %}
    <div id="edit-delete-buttons">
      <a
        href="{% url 'franchises_update' franchise.id %}"
        class="btn-lg btn-orange mr-2"
        >Edit Franchise</a
      >
      <a
        href="{% url 'franchises_delete' franchise.id %}"
        class="btn-lg btn-red-outline"
        >Delete Franchise</a
      >
    </div>
    {% endif %}
  </div>
</section>
<hr class="my-8" />
<section id="roster">
  <div class="mb-4">
    <h2 class="text-3xl">Roster</h2>
    {% if franchise.user == user %}
    <h3 class="text-xl">{{ franchise.player_set.all|length }} / 12 players</h3>
    {% endif %}
  </div>
  {% if franchise.player_set.all|length %}
  <!-- ROSTER HAS PLAYERS -->
  <table class="w-full text-left rtl:text-right mb-8 overflow-x-auto">
    <thead class="uppercase bg-slate-200">
      <tr>
        <th class="py-3 pl-6 pr-14">Full Name</th>
        <th class="py-3 pr-6">Position</th>
        <th class="hidden sm:table-cell py-3 pr-6">Height</th>
        <th class="hidden md:table-cell py-3 pr-6">Weight</th>
        {% if franchise.user == user %}
        <th class="py-3 pr-4">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody class="bg-slate-50">
      {% for player in franchise.player_set.all %}
      <tr class="border-b">
        <td class="py-3 pl-6 pr-14">
          {{ player.first_name }} {{ player.last_name }}
        </td>
        <td class="py-3 pr-6">
          {% if player.position %}{{ player.position }}{% else %}N/A{% endif %}
        </td>
        <td class="hidden sm:table-cell py-3 pr-6">
          {% if player.height %}{{ player.height }}{% else %}N/A{% endif %}
        </td>
        <td class="hidden md:table-cell py-3 pr-6">
          {% if player.weight %}{{ player.weight }}{% else %}N/A{% endif %}
        </td>
        {% if franchise.user == user %}
        <td class="py-3 pr-4">
          <form action="{% url 'add_player' franchise.id %}" method="POST">
            {% csrf_token %}
            <a
              href="{% url 'player_cut' franchise.id player.id %}"
              class="btn btn-red"
              >Cut</a
            >
          </form>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if franchise.user == user %}
  <!-- LOGGED IN USER IS FRANCHISE USER -->
  <a href="{% url 'players_search' franchise.id %}" class="btn-lg btn-orange"
    >Add Players</a
  >
  {% endif %} {% else %}
  <!-- ROSTER HAS NO PLAYERS -->
  {% if franchise.user == user %}
  <!-- LOGGED IN USER IS FRANCHISE USER -->
  <p class="mb-8 text-white">
    You can't build a dynasty without players! Start building your roster.
  </p>
  <a href="{% url 'players_search' franchise.id %}" class="btn-lg btn-orange"
    >Build Roster</a
  >
  {% else %}
  <p>This roster has no players yet. Check back soon!</p>
  {% endif %} {% endif %}
</section>

{% endblock %}

main_app/templates/franchises/index.html
{% extends 'base.html' %}

{% block content %}
<div id="heading" class="flex flex-col md:flex-row justify-between items-start mx-auto md:pl-6 mb-10 md:mb-4">
  <div class="md:w-3/5">
    <h1 class="text-4xl mb-2">All Franchises</h1>
    <p class="mb-4 md:mb-8 font-semibold">Select a team to check out their roster of players.</p>
  </div>
  <a href="{% url 'franchises_create' %}" class="btn md:btn-lg btn-green-outline">Create a Franchise</a>
</div>
<div id="container" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
  {% for franchise in franchises %}
  <div id="card" class="bg-white border rounded-lg overflow-hidden shadow-lg">
    <a href="{% url 'franchises_detail' franchise.id %}">
      {% for photo in franchise.photo_set.all %}
      {% if forloop.last %}
      <img class="aspect-3/2" src="{{ photo.url }}" alt="Photo for {{ franchise.city}} {{franchise.name }}">
      {% endif %}
      {% empty %}
      <img class="aspect-3/2" src="../../static/Assets/franchise-photo-placeholder.jpg" alt="Placeholder image of basketball hoop">
      {% endfor %}
      <div id="card-contents" class="px-6 pt-4 pb-8">
        <h2 class="font-body text-xl font-bold text-black">{{ franchise.city|capfirst }} {{ franchise.name }}</h2>
        <p class="text-slate-500 mb-4">Est. {{ franchise.established|date:'M d, Y' }}</p>
        <p class="italic">{{ franchise.motto }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

main_app/templates/franchises/my_index.html
{% extends 'base.html' %}

{% block content %}
<div id="heading" class="flex flex-col md:flex-row justify-between items-start mx-auto md:pl-6 mb-10 md:mb-4">
  <div class="md:w-3/5">
    <h1 class="text-4xl mb-2">My Franchises</h1>
    <p class="mb-4 md:mb-8 font-semibold">Select one of your created teams, add players to your roster, and build the next great NBA dynasty!</p>
  </div>
  <a href="{% url 'franchises_create' %}" class="btn md:btn-lg btn-green-outline">Create a New Franchise</a>
</div>
<div id="container" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
  {% for franchise in my_franchises %}
  <div id="card" class="bg-white border rounded-lg overflow-hidden shadow-lg">
    <a href="{% url 'franchises_detail' franchise.id %}">
      {% for photo in franchise.photo_set.all %}
      {% if forloop.last %}
      <img class="aspect-3/2" src="{{ photo.url }}" alt="Photo for {{ franchise.city}} {{franchise.name }}">
      {% endif %}
      {% empty %}
      <img class="aspect-3/2" src="../../static/Assets/franchise-photo-placeholder.jpg" alt="Placeholder image of basketball hoop">
      {% endfor %}
      <div id="card-contents" class="px-6 pt-4 pb-8">
        <h2 class="font-body text-xl font-bold text-black">{{ franchise.city|capfirst }} {{ franchise.name }}</h2>
        <p class="text-slate-500 mb-4">Est. {{ franchise.established|date:'M d, Y' }}</p>
        <p class="italic">{{ franchise.motto }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

main_app/templates/franchises/search.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-4xl font-bold mb-2">Build Your Roster</h1>
<p class="mb-8">Search from a database of players and add your favorites to the <span class="text-orange-50">{{ franchise.city }} {{ franchise.name }}</span>.</p>
<!-- Search form -->
<form action="{% url 'get_players' franchise_id=franchise_id %}" method="POST" class="w-full">
    {% csrf_token %}
    {{ form.first_name }}
  <button type="submit" class="btn btn-orange">Search</button>
</form>
{{ error_message }}
<!-- Render search results -->
{% if results.data|length %}
<table class="w-full text-left rtl:text-right mt-8 border overflow-x-auto">
  <thead class="uppercase bg-slate-200">
    <tr>
      <th class="py-3 pl-2 pr-14">Full Name</th>
      <th class="py-3 pr-6">Position</th>
      <th class="hidden sm:table-cell py-3 pr-6">Height</th>
      <th class="hidden md:table-cell py-3 pr-6">Weight</th>
      <th class="py-3 pr-4">Action</th>
    </tr>
  </thead>
  <tbody class="bg-slate-50">
    {% for player in results.data %}
    <tr class="border-b">
      <td class="py-3 pl-2 pr-14">{{ player.first_name }} {{ player.last_name }}</td>
      <td class="py-3 pr-6">
        {% if player.position %}{{ player.position }}{% else %}N/A{% endif %}</td>
      <td class="hidden sm:table-cell py-3 pr-6">{% if player.height%}{{ player.height }}{% else %}N/A{% endif %}</td>
      <td class="hidden md:table-cell py-3 pr-6">{% if player.weight %}{{ player.weight }}{% else %}N/A{% endif %}</td>
      <td class="py-3 pr-4">
        <form action="{% url 'add_player' franchise.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" value="{{ player.id }}" name="player-id" class="btn btn-green">
          <button type="submit" value="{{ player.id }}" class="btn btn-green">Add</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% elif request.method == 'POST' %}
<p class="mt-4 text-red-50">No results match your search, try again!</p>
{% endif %}
{% endblock %}